### PR TITLE
Add option to specify start LocalDateTime in nextRunList()

### PR DESCRIPTION
**Pull request by DJsushi**
I added the option for the library user to specify for themselves the `LocalDateTime` they want to use instead of always having `now()`.

### CODE REVIEW

**Review by Scogun — CHANGES_REQUESTED** [review]
Hi! Thank you for contributing!
However, PR is not fully ready:
1. There should be a unit test, for checking `start` different from now.
2. The information about this possibility should be added into README.md
3. The version should be increased. At least to `0.6.1`

Plus, we should decide what to do with `nextRun` property. For example, rename it into `nextRunFromNow` (in this case version should be `0.7.0`) and add new function `nexRun(start: LocalDateTime)`.

**Comment by DJsushi** [comment]
I'll add the tests and docs this weekend.

**Comment by DJsushi** [comment]
Sorry it took a while, but it's here.

**Comment by DJsushi** [comment]
Oops sorry. :)

**Review by Scogun — CHANGES_REQUESTED** [review]
1. `nextRun` property still works from now what is hidden from developers.
2. Version is not increased
3. After version increasing - `README.md` should be also update.

**Comment by Scogun** [comment]
@DJsushi would you like to finish the PR?

**Comment by Scogun** [comment]
Hello @DJsushi! The PR is open already for more than a half of year. Do you have plan to make it approvable?

**Pull request closed without merging**
